### PR TITLE
NL Amsterdam

### PR DESCRIPTION
**Pull request by paulovitorbal**
I started making some drafts about the Netherlands and Amsterdam.

I will keep updating this.

### CODE REVIEW

**Comment by djalmaaraujo** [comment]
@paulovitorbal Obrigado!! Muito boa sua contribuição, mas levanta uma questão: Deveria ser em pt-br?

**Comment by paulovitorbal** [comment]
Very good question. Maybe both. I can make a pt-br version, or I can translate everything. What do you think?

**Comment by djalmaaraujo** [comment]
@paulovitorbal Let me discuss with the admins, one second.

**Comment by djalmaaraujo** [comment]
@paulovitorbal If you don't mind, can you translate everything to pt-br? The goal here is to help all Brazilians. We can't assume that everybody knows English, but we know for a fact that they all know Portuguese.

Sorry for the extra work.

Thanks

**Comment by paulovitorbal** [comment]
Here it is!

**Comment by djalmaaraujo** [comment]
Show @paulovitorbal, obrigado!

**Pull request merged**
